name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: SemgusParser
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: SemgusParser
    - name: Publish (Linux)
      run: dotnet publish -c Release -o ../output/linux -r linux-x64 --self-contained true -p:PublishSingleFile=true
      working-directory: SemgusParser
    - name: Upload (Linux)
      uses: actions/upload-artifact@v2
      with:
        name: semgus-parser-linux
        path: output/linux
    - name: Publish (Windows)
      run: dotnet publish -c Release -o ../output/win -r win-x64 --self-contained true -p:PublishSingleFile=true
      working-directory: SemgusParser
    - name: Upload (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: semgus-parser-win
        path: output/win
    - name: Publish (macOS)
      run: dotnet publish -c Release -o ../output/osx -r osx-x64 --self-contained true -p:PublishSingleFile=true
      working-directory: SemgusParser
    - name: Upload (macOS)
      uses: actions/upload-artifact@v2
      with:
        name: semgus-parser-osx
        path: output/osx
